### PR TITLE
Fix: properly check travis-ci.com 'green' status

### LINKED ISSUE #112: Travis status check always failing while doing a publish
recently all attempts to do a `@jarvis publish ...` end up failing despite the :green_circle: CI status on the commit.
likely related to the recent travis-ci.org -> travis-ci.com switch, we should make sure CI status check works.
the current work-around is to always use `@travis publish --no-check-build` ... :crying_cat_face: 

*NOTE: Jarvis might simply end up not detecting [travis and falling back to jenkins check?](https://github.com/elastic/jarvis/blob/v0.4.3/lib/jarvis/commands/publish.rb#L87-L92)*

### PR DESCRIPTION
**Pull request by kares**
the legacy travis-ci.org was using GH statuses API, while travis-ci.com switched to posting check-runs

deprecation post from Travis CI: https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories

resolves #112

### CODE REVIEW

**Comment by kares** [comment]
have tested :green_circle: CI and :red_circle: manually (locally - without actually publishing)

File: lib/jarvis/commands/publish.rb [hunk 1]
```diff
@@ -69,29 +69,36 @@ def execute
...
-        end]
-
-        if current_states.any?
-          unsuccessful_statuses = Hash[current_states.select {|context,state| state != "success" }]
-          if unsuccessful_statuses.any?
-            logger.error("Cannot publish, some github commit hooks are not in a successful state.", :statuses => unsuccessful_statuses)
-            next
+        travis_check_run = nil
+        response = Octokit.check_runs_for_ref(project.path, workdir_sha1, filter: 'latest') # status: 'completed'
+        if response.total_count > 0
```
Comment (jsvd) [inline lib/jarvis/commands/publish.rb:75]: maybe can get rid of this external conditional? as `check_runs.find` in line 77 looks for a check of travis-ci.com, that should be enough, we don't need to have a separate error message to signal there are zero checks. as we already have one to signal no "travis-ci.com" checks.

File: lib/jarvis/commands/publish.rb [hunk 2]
```diff
@@ -69,29 +69,36 @@ def execute
...
+          # expect only one, even if check re-run, due `filter: 'latest'`
+          if travis_check_run = response.check_runs.find { |check_run| check_run.details_url.index('travis-ci.com') }
+            if travis_check_run.status != 'completed'
+              logger.error("Cannot publish - travis-ci check hasn't completed yet", status: travis_check_run.status)
+              travis_check_run = false
+            elsif travis_check_run.conclusion != 'success'
+              logger.error("Cannot publish - travis-ci hasn't completed with a 'success'", conclusion: travis_check_run.conclusion)
+              travis_check_run = false
+            end
```
Comment (jsvd) [inline lib/jarvis/commands/publish.rb:84]:
```suggestion
            else
              logger.error("Cannot publish - travis-ci check has an unknown state", status: travis_check_run.status, conclusion: travis_check_run.conclusion)
            end
```

Comment (kares) [reply lib/jarvis/commands/publish.rb]: that won't work since for the found `travis_check_run = response.check_runs.find` we need to assert conditions are met: `travis_check_run.status == 'completed'` (built isn't still running) and `travis_check_run.conclusion == 'success'` (run isn't in a :red_circle: state). 

`conclusion == 'success'` might be enough - anyhow having all checks explicitly should be the safer option...

Comment (jsvd) [reply lib/jarvis/commands/publish.rb]: so we can just mark this as a failed check, and set `travis_check_run = false`?

Comment (kares) [reply lib/jarvis/commands/publish.rb]: yeah we can do so - thought a separate message about "built still running" makes sense but I am fine with just logging `status:` and `conclusion:` at once - however you need to be aware what each means to understand why publish failed.

Comment (jsvd) [reply lib/jarvis/commands/publish.rb]: right. the whole intent of this edit was to not leave the if/elsif claus without an `else`. happy to accept any other suggestion to handle this scenario.

Comment (kares) [reply lib/jarvis/commands/publish.rb]: okay, we can borrow one from the code bellow :stuck_out_tongue:

**Review by jsvd — APPROVED** [review]
LGTM
